apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tu61p23tb-python 
  janus-idp.io/tekton: tu61p23tb-python
  backstage.io/kubernetes-id: tu61p23tb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tu61p23tb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml