apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tu61p23tb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tu61p23tb-python 
  name: tu61p23tb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tu61p23tb-python 
